-- migration_003_phase12_order_reservation.sql
-- SQL Server (BrandCreator_HUBDB)

SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET XACT_ABORT ON;
BEGIN TRAN;

IF OBJECT_ID('dbo.OrderItems','U') IS NOT NULL DROP TABLE dbo.OrderItems;
IF OBJECT_ID('dbo.Orders','U') IS NOT NULL DROP TABLE dbo.Orders;
IF OBJECT_ID('dbo.PaymentEvents','U') IS NOT NULL DROP TABLE dbo.PaymentEvents;
IF OBJECT_ID('dbo.OutboxEvents','U') IS NOT NULL DROP TABLE dbo.OutboxEvents;

IF OBJECT_ID('dbo.Orders','U') IS NULL
CREATE TABLE dbo.Orders (
  OrderId BIGINT IDENTITY(1,1) PRIMARY KEY,
  OrderRef NVARCHAR(100) NOT NULL UNIQUE,
  CustomerEmail NVARCHAR(255) NOT NULL,
  Status NVARCHAR(30) NOT NULL DEFAULT 'PENDING', -- PENDING/CONFIRMED/CANCELLED/FAILED
  TotalAmount DECIMAL(18,2) NOT NULL DEFAULT 0,
  Currency NVARCHAR(10) NOT NULL DEFAULT 'BDT',
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

IF OBJECT_ID('dbo.OrderItems','U') IS NULL
CREATE TABLE dbo.OrderItems (
  OrderItemId BIGINT IDENTITY(1,1) PRIMARY KEY,
  OrderId BIGINT NOT NULL,
  ProductId INT NOT NULL,
  Qty INT NOT NULL,
  UnitPrice DECIMAL(18,2) NOT NULL,
  LineTotal AS (Qty * UnitPrice) PERSISTED,
  CONSTRAINT CK_OrderItems_QtyPositive CHECK (Qty > 0),
  CONSTRAINT FK_OrderItems_Orders FOREIGN KEY (OrderId) REFERENCES dbo.Orders(OrderId),
  CONSTRAINT FK_OrderItems_Products FOREIGN KEY (ProductId) REFERENCES dbo.Products(ProductId)
);

IF OBJECT_ID('dbo.PaymentEvents','U') IS NULL
CREATE TABLE dbo.PaymentEvents (
  PaymentEventId BIGINT IDENTITY(1,1) PRIMARY KEY,
  Provider NVARCHAR(50) NOT NULL, -- BKASH/NAGAD/STRIPE/etc
  EventType NVARCHAR(50) NOT NULL, -- AUTH/CAPTURE/FAIL/CANCEL
  EventRef NVARCHAR(150) NOT NULL, -- gateway txn/ref
  OrderRef NVARCHAR(100) NOT NULL,
  IdempotencyKey NVARCHAR(150) NOT NULL,
  PayloadJson NVARCHAR(MAX) NULL,
  Processed BIT NOT NULL DEFAULT 0,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT UQ_PaymentEvents_Idempotency UNIQUE (IdempotencyKey)
);

IF OBJECT_ID('dbo.OutboxEvents','U') IS NULL
CREATE TABLE dbo.OutboxEvents (
  OutboxId BIGINT IDENTITY(1,1) PRIMARY KEY,
  EventType NVARCHAR(80) NOT NULL, -- ORDER_CONFIRMED/ORDER_CANCELLED/LOW_STOCK/etc
  AggregateType NVARCHAR(50) NOT NULL, -- ORDER/PRODUCT
  AggregateId NVARCHAR(100) NOT NULL,
  PayloadJson NVARCHAR(MAX) NOT NULL,
  Status NVARCHAR(20) NOT NULL DEFAULT 'PENDING', -- PENDING/SENT/FAILED
  RetryCount INT NOT NULL DEFAULT 0,
  LastError NVARCHAR(1000) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  SentAt DATETIME2 NULL
);

COMMIT;
GO
